name: Bump the release version

runs:
  using: "composite"
  steps:
    - name: Get latest tag
      id: get_latest_tag
      shell: bash
      run: |
        TAG=$(git describe --tags --abbrev=0 || echo "v1.0.0")
        echo "Latest tag: $TAG"
        echo "tag=$TAG" >> $GITHUB_OUTPUT

    - name: Parse next version
      id: bump_version
      shell: bash
      run: |
        TITLE="${{ github.event.pull_request.title }}"
        CURRENT_TAG="${{ steps.get_latest_tag.outputs.tag }}"
        VERSION="${CURRENT_TAG#v}"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        cp .github/actions/bump_version/version.sh version.sh
        chmod +x version.sh
        if [[ $TITLE == *major* ]]; then
          ./version.sh major
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_OUTPUT
        elif [[ $TITLE == *minor* ]]; then
          ./version.sh minor
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_OUTPUT
        else
          ./version.sh
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_OUTPUT
        fi
          
    - name: Create and push new tag
      shell: bash
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git tag ${{ steps.bump_version.outputs.NEW_VERSION }}
        git push origin ${{ steps.bump_version.outputs.NEW_VERSION }}
        