name: Deploy the application on GKE cluster

on:
    workflow_call:
        inputs:
           namespace:
            default: dev
            description: "Environment on which application needs to be deployed"
            type: string
            required: true
jobs:
    Deploy:
        permissions:
          id-token: 
            write
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Authenticate to GCP account
              uses: 'google-github-actions/auth@v2'
              with:
                project_id: ${{ secrets.PROJECTID }}
                workload_identity_provider: ${{ secrets.workload_identity_provider }}
                service_account: ${{ secrets.service_account }}

            - name: 'Set up Cloud SDK'
              uses: 'google-github-actions/setup-gcloud@v2'
              with:
                version: '>= 363.0.0'
            - name: Install the gcloud and kubectl and also deploy the app using helm
              run: |
                IMAGE_TAG=$(cat pom.xml | grep "SNAPSHOT" | sed 's/<version>//g' | awk -F'</version>' '{print $1}'|sed 's/-SNAPSHOT//')
                IMAGE_TAG=$(echo $IMAGE_TAG | sed -e 's/^[ \t]*//')
                echo $IMAGE_TAG
                gcloud --version
                gcloud components install kubectl
                gcloud container clusters list --project gcp-gke-453620
                gcloud container clusters get-credentials infra-dev-gke-cluster --region europe-west3 --project gcp-gke-453620
                kubectl get nodes
                cd helm
                helm version
                helm upgrade -i spring-boot -f values.yaml --set image.tag=${IMAGE_TAG} . --namespace ${{ inputs.namespace }}
       